# Week 1 Labs

## PyTorch and Tensors

### Problem 1

Create a Python array of array or arrays (three levels of nesting). The inner most arrays should have 3 elements each the middle should have 2 and the outer should have 2 elements as represented below:

```
Array( 
    Array( 
        Array( 1, 2, 3 ), 
        Array( 4, 5, 6 ), 
    ),
    Array( 
        Array( 7 , 8 , 9  ), 
        Array( 10, 11, 12 ),
    ),
)
```

Write Python code to access each of the following elements: 2, 6, 8, 11 (one line to access and print each of these). Be sure to first initialise the array of array of arrays. 


In [ ]:
a=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(a[0][0][1])
print(a[0][1][2])
print(a[1][0][1])
print(a[1][1][1])

2
6
8
11


### Problem 2

Create and print the following tensors using one line of code only, *without the use of numpy (or python) arrays*: 

1.   A 1 dimentional tensor with 8 0's
2.   A 1 dimentional tensor with 8 1
3.   A 1 dimentional tensor with 8 random numbers
4.   A 1 dimentional tensor with 8 random numbers between [0, 10)
5.   A 1 dimentional tensor with 8 random integers between [0, 10)
6.   A 2 dimentional tensor consisting of all numbers [1, 9] with 3 rows.


In [ ]:
import torch
print(torch.zeros(8))
print(torch.ones(8))
print(torch.rand(8))
print(torch.rand(8)*10)
print((torch.rand(8)*10).round())
print( torch.arange( 1, 10, 1).reshape((3,3)))

tensor([0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0.2064, 0.5255, 0.7734, 0.8606, 0.3930, 0.5055, 0.3250, 0.7754])
tensor([3.3726, 0.3988, 5.8357, 4.0913, 4.3729, 1.9862, 8.1008, 3.7434])
tensor([ 3.,  7., 10.,  6.,  1.,  7.,  5.,  6.])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### Problem 3

### Problem 3a
Multiply the following matrices using PyTorch

```
| 1,  3 |      | 1, 2 |
| 2, -1 |  x   | 3, 3 | 
```

### Problem 3b

Initialise a tensor using the following code:
```
pytorch_tensor = torch.tensor( 
                       [
                         [20., 87., 78., 35., 84.],
                         [64., 71., 42., 38., 86.],
                         [92.,  8., 11., 43., 40.]
                       ]
)

```

Using splicing operations (i.e., ```pytorch_tensor[:,:]```) splice the above tensor (and print) the following: 

1. 
```  
  20., 87., 78., 35., 84.
```

2. 
```  
  20., 64., 92.
```

3. 
```  
  87., 78.
  71., 42.
   8., 11.
```

4. 
```  
  84., 86., 40.
```


In [ ]:
a=torch.tensor([[1.,3.],
               [2.,-1.]])
b=torch.tensor([[1.,2.],
               [3.,3.]])
print(a.mm(b))
pytorch_tensor = torch.tensor( 
                       [
                         [20., 87., 78., 35., 84.],
                         [64., 71., 42., 38., 86.],
                         [92.,  8., 11., 43., 40.]
                       ]
)
print(pytorch_tensor[0,:])
print(pytorch_tensor[:,0])
print(pytorch_tensor[:,1:3])
print(pytorch_tensor[:,-1])

tensor([[10., 11.],
        [-1.,  1.]])
tensor([20., 87., 78., 35., 84.])
tensor([20., 64., 92.])
tensor([[87., 78.],
        [71., 42.],
        [ 8., 11.]])
tensor([84., 86., 40.])


## Pre-Trained Models

We are going to work with some pre-trained models. Before that, we need some tools to download and manipulate files on Google Colab. 

### Files and Linux commands - Google CoLab

**Problem 4**

Navigate to the following URL: https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch2/horse.jpg 

Download this image to your CoLab instance. You might find the following resources helpful: 

1. [Google Colab Shell](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.05-IPython-And-Shell-Commands.ipynb)
2. [wget](https://www.gnu.org/software/wget/manual/wget.html#Simple-Usage)


Use the file explorer on the left (the folder icon) to locate the file.

**Problem 5**

Install the following python packages to your colab instance: 
1. [Huggingface Transformers](https://huggingface.co/docs/transformers/installation) *NOTE*: you will NOT need to install an environment. You can do this directly with ```pip```. 
2. [Hugginface Datasets](https://huggingface.co/docs/datasets/installation) 



In [ ]:
!pip install transformers
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 38.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 17.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 76.9 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.8/462.8 KB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 KB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 12.1 MB/s eta 0:00:00
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


### Problem 6


The following code initialises a version of the popular model called T5 that has been trained to answer trivia questions and runs a question through it. 

```
from transformers import AutoTokenizer, AutoModelWithLMHead

model = AutoModelWithLMHead.from_pretrained("deep-learning-analytics/triviaqa-t5-base")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = model.to(device)

base_tokenizer = AutoTokenizer.from_pretrained("t5-base", use_fast=False)

preprocess_text = "Which singer's real name is Stefani Joanne Angelina Germanotta?"

print( "Your question: ", preprocess_text ) 

tokenized_text = base_tokenizer.encode(preprocess_text, return_tensors="pt").to(device)

outs = model.generate(
            tokenized_text,
            max_length=20,
            num_beams=4,
            early_stopping=True
           )

dec = [base_tokenizer.decode(ids) for ids in outs]
prediction = dec[0].lstrip().rstrip().replace( "<pad> ", "" ).replace( "</s>", "" ).replace( "<extra_id_0> ", "" )

print( prediction) 

```

### Problem 6 a

Paste this code into a code block and run it. Is the answer correct?

### Problem 6 b

Restructure this code (using functions) so you can run it on multiple questions without having to reinitialise the model over and over again. Now run the following questions through the model: 

```
      "Which singer's real name is Stefani Joanne Angelina Germanotta?", 
      "What is the stage name of Stefani Joanne Angelina Germanotta?", 
      "Who sang the song Thriller which won the Grammy Award for Best Music Video?", 
      "Where is the University of Bath located?"
```

Before juding this model too harshly, read about the [different T5 models](https://huggingface.co/docs/transformers/model_doc/t5) and the number of parameters they have. 

In [ ]:
from transformers import AutoTokenizer, AutoModelWithLMHead

def predictions(questions):
  answer=[]
  for i in questions:
    tokenized_text = base_tokenizer.encode(i, return_tensors="pt").to(device)
    outs = model.generate(
            tokenized_text,
            max_length=20,
            num_beams=4,
            early_stopping=True
           )
    dec = [base_tokenizer.decode(ids) for ids in outs]
    prediction = dec[0].lstrip().rstrip().replace( "<pad> ", "" ).replace( "</s>", "" ).replace( "<extra_id_0> ", "" )
    answer.append(prediction)
  return answer 

model = AutoModelWithLMHead.from_pretrained("deep-learning-analytics/triviaqa-t5-base")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = model.to(device)

base_tokenizer = AutoTokenizer.from_pretrained("t5-base", use_fast=False)

preprocess_text = "Which singer's real name is Stefani Joanne Angelina Germanotta?"

print( "Your question: ", preprocess_text ) 

tokenized_text = base_tokenizer.encode(preprocess_text, return_tensors="pt").to(device)

outs = model.generate(
            tokenized_text,
            max_length=20,
            num_beams=4,
            early_stopping=True
           )

dec = [base_tokenizer.decode(ids) for ids in outs]
prediction = dec[0].lstrip().rstrip().replace( "<pad> ", "" ).replace( "</s>", "" ).replace( "<extra_id_0> ", "" )

questions = ["Which singer's real name is Stefani Joanne Angelina Germanotta?", 
      "What is the stage name of Stefani Joanne Angelina Germanotta?", 
      "Who sang the song Thriller which won the Grammy Award for Best Music Video?", 
      "Where is the University of Bath located?"]
print(questions[1])
print(predictions(questions))
print( prediction) 

/usr/local/lib/python3.8/dist-packages/transformers/models/auto/modeling_auto.py:1248: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn(


/usr/local/lib/python3.8/dist-packages/transformers/models/t5/tokenization_t5_fast.py:155: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(


Your question:  Which singer's real name is Stefani Joanne Angelina Germanotta?
What is the stage name of Stefani Joanne Angelina Germanotta?
['Lady Gaga', 'Lady Ga Ga', 'Mike Oldfield', 'Bristol']
Lady Gaga


### Problem 7

Navigate to [Chapter 2](https://learning.oreilly.com/library/view/deep-learning-with/9781617295263/Text/02.xhtml#sigil_toc_id_22) of book Deep Learning with PyTorch. 

Carefully read and run the model described in Section 2.1 (up to 2.1.5). You should be able to detect bobby. 

Here are a couple of things that'll help (these will only make sense once you read the chapter. 


Split the ```preprocess``` function provided as follows so you can visualise the output of the resize and crop. 

```
preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
])

tensorize = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
           mean=[0.485, 0.456, 0.406],
           std=[0.229, 0.224, 0.225]
        )
])
```

You can download the image of bobby from: https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch2/bobby.jpg

(don't forget to use ```wget```!) 

You can download a file containing the imagenet classes from: https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt 

The files you download are downloaded to ```'/content/```, as in ```/content/bobby.jpg```


You can output the image but having img (or wherever you save the image) on a seperate cell in the notebook.


In [ ]:
from torchvision import models
alexnet = models.AlexNet()
resnet = models.resnet101(pretrained=True)
from torchvision import transforms
preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
])

tensorize = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(
           mean=[0.485, 0.456, 0.406],
           std=[0.229, 0.224, 0.225]
        )
])
from PIL import Image

!wget -O horse.jpg 'https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch2/horse.jpg'
!pwd
img=Image.open("../content/horse.jpg")
img_t = preprocess(img)
img_t = tensorize(img_t)
import torch
batch_t = torch.unsqueeze(img_t, 0)
resnet.eval()
out = resnet(batch_t)
with open('../content/sample_data/imagenet_classes.txt') as f:
  labels = [line.strip() for line in f.readlines()]
_, index = torch.max(out, 1)
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index[0]], percentage[index[0]].item()
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

--2023-02-21 15:39:03--  https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch2/horse.jpg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 385347 (376K) [image/jpeg]
Saving to: ‘horse.jpg’

horse.jpg           100%[===================>] 376.32K  --.-KB/s    in 0.006s  

2023-02-21 15:39:03 (58.3 MB/s) - ‘horse.jpg’ saved [385347/385347]

/content


FileNotFoundError: ignored

### Problem 8 a

Now run the model on the following image: https://upload.wikimedia.org/wikipedia/commons/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg 


### Problem 8 b

Now run the model on the same image, but use the following updated version of the transform to be able to crop the image correctly.

```
def crop800(image):
    return crop(image, 5, 40, 180, 180)

preprocess = transforms.Compose([
        transforms.Lambda(crop800),
        transforms.Resize(256),
])
```



In [ ]:
img2 = Image.open("../content/sample_data/gs.jpg")
def crop800(image):
    return image.crop((5, 40, 180, 180))

preprocess = transforms.Compose([
        transforms.Lambda(crop800),
        transforms.Resize(256),
])

img_t2 = preprocess(img2)
img_t2 = tensorize(img_t2)
import torch
batch_t2 = torch.unsqueeze(img_t2, 0)
resnet.eval()
out = resnet(batch_t2)
with open('../content/sample_data/imagenet_classes.txt') as f:
  labels = [line.strip() for line in f.readlines()]
_, index = torch.max(out, 1)
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index[0]], percentage[index[0]].item()

('German shepherd', 70.9229736328125)

### Problem 9

Now classify the following images. Make necessary changes to the crop transform to help the model classify the images correctly. 

1. https://cdn.shopify.com/s/files/1/0137/6210/1348/collections/87399596132_3000x.jpg?v=1629297832
2. https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Chou-fleur_02.jpg/1920px-Chou-fleur_02.jpg


In [ ]:
img3=Image.open("../content/sample_data/cauli.jpg")
img_t3 = preprocess(img3)
img_t3 = tensorize(img_t3)
import torch
batch_t3 = torch.unsqueeze(img_t3, 0)
resnet.eval()
out = resnet(batch_t3)
with open('../content/sample_data/imagenet_classes.txt') as f:
  labels = [line.strip() for line in f.readlines()]
_, index = torch.max(out, 1)
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index[0]], percentage[index[0]].item()

('kite', 18.204051971435547)

### Problem 9

Run the CycleGAN model described in Section 2.2.

Included below is the code that is mysteriously missing from Section 2.2 of the book. 

You will additionally need the model weights available at https://github.com/deep-learning-with-pytorch/dlwpt-code/raw/master/data/p1ch2/horse2zebra_0.4.0.pth (use ```wget``` to download)

You can download the image to transfer from https://raw.githubusercontent.com/deep-learning-with-pytorch/dlwpt-code/master/data/p1ch2/horse.jpg 



### Problem 10

Run the model detailed in Section 2.3 of the book. 

You will need to clone the git repository containing the model. You can use: 

```
!git clone https://github.com/deep-learning-with-pytorch/ImageCaptioning.pytorch.git
```

You can navigate to the correct directory using: 

```
%cd /content/ImageCaptioning.pytorch/
```
(Consider why you must use "%" instead of "!" as one does in all previous commands) 



### Problem 11

The following code snippet can be used to calculate the gradiant of ```y = 12 - (4 * x) + (2 * x**2 )``` at ```x = 1```
```  
  x = torch.tensor( 1 , dtype=float ) 
  x.requires_grad = True
  y = 12 - (4 * x) + (2 * x**2 )
  y.backward() 
  print( x.grad ) 
```

Write a loop to find the gradient at values of x between -10 and 10. store x, y, and x.grad in arrays so you can plote them using the following code snippet: 

```
import matplotlib
import matplotlib.pyplot as plt
plt.scatter(xs, ys )
plt.scatter(xs, gxs)
plt.show()
```

### Problem 11

Repeat the above for the following equestion: 

```
y = 12 + (40 * x) - (12 * x**2 ) - ( 0.1 * x**3) + ( 1 * x**4 ) 
```  

**Be sure to increment the value of x by 0.1**